- name: Install snmpd (Debian)
  when: ansible_distribution == 'Debian'
  apt: name=snmpd state=latest
  notify: restart snmpd
- name: Install net-snmp (FreeBSD)
  when: ansible_distribution == 'FreeBSD'
  pkgng: name=net-snmp state=present
  notify: restart snmpd

- name: Enable service (FreeBSD)
  when: ansible_distribution == 'FreeBSD'
  lineinfile: dest=/etc/rc.conf regexp=^snmpd_enable= line=snmpd_enable=YES
- name: Set config file (FreeBSD)
  when: ansible_distribution == 'FreeBSD'
  lineinfile: dest=/etc/rc.conf regexp=^snmpd_conffile= line=snmpd_conffile=/etc/snmp/snmpd.conf

- name: Creates etc/ directory
  file: path=/etc/snmp state=directory
  notify: restart snmpd

- name: Paste config
  template: src=snmpd.conf dest=/etc/snmp/snmpd.conf
  notify: restart snmpd
- name: Paste distro script
  template: src=distro dest=/usr/bin/distro
  notify: restart snmpd
